### ISSUE TITLE
Unknown plugin with webpack

### ISSUE THREAD

**Issue by ianengelbrecht** [dzwillia/vue-simple-spinner#10]
I get this error when using this component with a webpack build: Unknown plugin "transform-object-rest-spread". It seems it depends on a deprecated version of babel's plugins or something.

**Comment by dzwillia** [comment]
Are you trying to run this in a dev environment? If you're just using ES6 imports or require(), this should never get referenced as it is just a dev dependency.

**Comment by ianengelbrecht** [comment]
Yes, very strange that it’s somehow referencing that extension. I am
running a webpack dev environment for this. I’ve used the webpack-simple
Vue template project.

**Comment by dzwillia** [comment]
Did you run `npm install vue-simple-spinner` or `yarn add vue-simple-spinner`? Once you've done that, you should be able to import or require `vue-simple-spinner`. You can follow the README at that point. That's what you would want to do to get going with it.

**Comment by shiragold** [comment]
Same here - running npm run dev raises:
Unknown plugin "transform-runtime"
I could only get it working by removing that dependency from spinner's .babelrc

**Comment by dzwillia** [comment]
I'll look into this. I'm a bit miffed as to why this would be the case. If you've run `npm install` or `yarn` in the root folder, it should install this Babel plugin. If you look at line 40 of the **package.json** file, you'll see this: `"babel-plugin-transform-runtime": "^6.23.0"`, so the plugin should be included.

**Comment by stijnvanbossuyt** [comment]
Any news on this?

**Comment by dzwillia** [comment]
I'm going to look into cleaning up some of the babel plugins (this one included). Once I do that and have pushed a new release, I'll let you know and then we can see if this issue is resolved.

**Comment by dzwillia** [comment]
Hi all,

I've cleaned up the babel dependencies (including removing the `babel-runtime` plugin) as of the v1.2.10 release. Please let me know if this resolves your issues.

Thanks much!

Dave.

**Comment by dzwillia** [comment]
I've cleaned this up and am going to close due to inactivity. Please let me know if there are any other issues.
