### ISSUE TITLE
Line Size behavior

### ISSUE THREAD

**Issue by wcarron27** [dzwillia/vue-simple-spinner#11]
Just a thought:

When customizing the spinners, I had set size="massive". Then I had tried to adjust the line-size attribute and found that it was not doing anything. Only when I dug into the source code did I realize that if the `size` attribute is one of your defaults: e.g. "massive", the line-size defaults to 3, iirc.

When I changed to size to size="55", I was able to set the line-size.

Obviously, that's really weird behavior. Would expect them to be independent.

**Comment by dzwillia** [comment]
I can see how that might be a big confusing. The `size` props were meant to be "one stop shop" sizes so you didn't have to change a bunch of props. Perhaps I'll make the `size` prop set defaults that can be overridden by the other props.

**Comment by dzwillia** [comment]
@wcarron27 I'm gonna close this out. I think this is something more to be aware of than it is a bug in the component. Thanks for your input!
