### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by lasthrun** [dzwillia/vue-simple-spinner#12]
hello! your spinner is great and easy to use, good job! but i think it can be better.

1. i can't find the API in the document. i had to look up the source code to find out what they are. i think we should write it down.

2. i saw we had used style on the spinner, i think we should use class. you know, almost every time, the third party framework do not meet our requirement. we always need to give it some new style by class or style. but if we using style by style, we can not cover your style by a easy way. so i think change to using class will be more user friendly.

**Comment by dzwillia** [comment]
Hi there --

Thanks for using the spinner -- I'm glad you like it and have found it easy to use! You certainly have a point regarding the documentation -- I've been meaning to include code snippet for each of the examples for some time now and have been tied up with other work lately.

Regarding the usage of classes vs. styles, I understand where you are coming from, however, the idea here is to create a spinner with literally no dependencies. As soon as you involve CSS, the component is no longer a single "drop-in" component. The styles for the spinner can be configured in any manner possible in CSS using the props.

That being said, there are two classes `vue-simple-spinner` for the spinner and `vue-simple-spinner-text` for the text that are part of the component in the event you want to add styling that goes beyond what is provided in the props.

I hope this is helpful to you!

**Comment by lasthrun** [comment]
if you want to use style, we must promise all style value are from the props. as i saw, some style are relate with size, it is hard to control. so, make all style with their own props, it will be more user friendly.

**Comment by dzwillia** [comment]
The calculated styles do indeed come from the props. If you want to add your own styles, you could simply do this on the wrapper element. Hope that helps.
