### ISSUE TITLE
Unknown custom element: <vue-simple-spinner>

### ISSUE THREAD

**Issue by stijnvanbossuyt** [dzwillia/vue-simple-spinner#13]
Using Webpack & Typescript.

```
import Spinner from 'vue-simple-spinner';

@Component({
    components: {
        Spinner
    }
})
```

**Comment by stijnvanbossuyt** [comment]
Have to pass it in like this not really sure why though.. Name is defined inside the spinner component..

@Component({
    components: {
        'vue-simple-spinner' : Spinner
    }
})

**Comment by dzwillia** [comment]
Yeah, this is definitely strange. With ES6 imports, you shouldn't need to use the default export name of the component (after all, that's kind of one of the big pluses of default exports). I don't use TypeScript in any of my projects, so I'm wondering if it has something to do with that.

**Comment by nwsm** [comment]
I also get unknown custom element unless I specify name. Not using typescript.

**Comment by windmaomao** [comment]
I got it too, somehow, I need to do this to get it working

```
  import VueSimpleSpinner from 'vue-simple-spinner'
```

**Comment by dzwillia** [comment]
Hi all,

I've just updated the component and removed the `name` from it. Could someone check to see if this resolves your issue?

Thanks!

**Comment by jekel** [comment]
Hello
same for me, works only if it is imported like told before by @windmaomao

**Comment by dzwillia** [comment]
Hi all!

I'd love to fix this issue, but I'll be honest, I really don't know what to do to fix it. If someone has a good sense of what to do and can test it to make sure it works, I'd be more than willing to merge their pull request.

Thanks!

Dave.

**Comment by dipapazacharias** [comment]
I don't think there is something to fix here. It's not a javascript ES6 thing, but a Vue.js thing. You can't import  a component and and include it in your parent component declarationwith a certain name, and then use it on your parent component's template with another.

For example, it will work fine if you do:

<template>
  <spinner></spinner>
</template>

<script>
import Spinner from 'vue-simple-spinner';
export default {
  name: 'ParentComponent',
  components: { Spinner }
}
</script>

or do it with 
<vue-simple-spinner></vue-simple-spinner>
...
import VueSimpleSpinner
..
components: { VueSimpleSpinner },
..

I think it's just the instructions are misleading, and should be adjusted to one of the above choices.

**Comment by Kocal** [comment]
Did you tried to remove the line `libraryExport: 'default'` from your `webpack.config.dist.js`?

**Comment by lggwettmann** [comment]
I had to google for a tutorial to get this to work :/ This is what worked in the end for me:

```
import Spinner from 'vue-simple-spinner'
Vue.component('vue-simple-spinner', Spinner)
<vue-simple-spinner></vue-simple-spinner>
```

Thanks for the great component!
