### ISSUE TITLE
Add .babelrc to .npmignore

### ISSUE THREAD

**Issue by CookiesEater** [dzwillia/vue-simple-spinner#14]
Hi!
Thanks for great spinner :)

Please, add .babelrc to .npmignore file (and maybe some other, like /examples/ and /build/, that not needed in end package). Because according to babel [lookup behaviour](https://babeljs.io/docs/usage/babelrc/#lookup-behavior) I can't include component directly if I haven't installed some babel plugins listed in .babelrc of this package.

Some example:
If I try do this:
`import Spinner from 'vue-simple-spinner/src/components/Spinner.vue';`
and in my app not installed babel plugin "transform-object-rest-spread" I will get error "Unknown plugin "transform-object-rest-spread" specified in ..."

**Comment by dobromir-hristov** [comment]
You should not import the src file in the first place.

**Comment by dzwillia** [comment]
Agreed, @dobromir-hristov -- thanks for chiming in! Files in the `src` folder are there for development. If you follow the [installation instructions](https://github.com/dzwillia/vue-simple-spinner#installation) you should be good to go!
