### ISSUE TITLE
[Vue warn]: Invalid prop: custom validator check failed for prop "size"

### ISSUE THREAD

**Issue by barbrady123** [dzwillia/vue-simple-spinner#17]
"size" property being set to one the standard strings "tiny", as such:

`<vue-simple-spinner size="tiny"></vue-simple-spinner>`

Results in the run-time warning "[Vue warn]: Invalid prop: custom validator check failed for prop "size"

Tested a few other values ("small", "12", etc...) and this validator error is always present.

**Comment by dzwillia** [comment]
Whoops! Thanks for the heads up on this. I'll see if I can spin a new build here in the next couple of days.

**Comment by dzwillia** [comment]
Hmm... I just looked into the issue and I can't replicate it at all.

I'm not getting that warning when I test it on localhost. In addition, I don't see the error on either the examples page (https://dzwillia.github.io/vue-simple-spinner/examples/) or the JsFiddle page (http://jsfiddle.net/dzwillia/kc5ka8zu). You can see that I use quite a few different values for the `size` prop in the examples.

If you take a look at the source for this component, there is no prop validation specified.

```
      'size': {
        // either a number (pixel width/height) or 'tiny', 'small',
        // 'medium', 'large', 'huge', 'massive' for common sizes
        default: 32
      },
```

Is it possible you have some sort of global mixin specified which is causing this to happen?

**Comment by barbrady123** [comment]
Sorry, just realized this is still open, closing...this ended up being something completely unrelated.  I had another attribute on another object in the same component also set to 'tiny', which was invalid for that component.  Thank you!
