### ISSUE TITLE
Is there some dependency missing?

### ISSUE THREAD

**Issue by Gr33nbl00d** [dzwillia/vue-simple-spinner#2]
error: Cannot find module '!!../../node_modules/css-loader/index.js!../../node_modules/vue-loader/lib/style-compiler/index.js?{"id":"data-v-f8f101d2","scoped":false,"hasInlineConfig":true}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Spinner.vue' from **

**Comment by Gr33nbl00d** [comment]
Just found out it seems to work if i exchange vue-simple spinner.js with vue-simple-spinner.min.js
so vue-simple-spinner.min.js seems to work

**Comment by dzwillia** [comment]
Hi there --

Thanks for your interesting in using the spinner. Glad you were able to get it working.

The spinner component doesn't have any dependencies other the Vue.js.

  * If you're using ES6 imports, you can see how to do that in the [ES6 Code Example](https://github.com/dzwillia/vue-simple-spinner#es6).

  * If you're using a global script tag, you should be able to use either of the JS files in the `dist` folder: vue-spinner.js or vue-spinner.min.js. The latter is has just been minified for you.

Let me know if there's anything else I can do for you.

Hope you find the spinner useful!

**Comment by Gr33nbl00d** [comment]
I know im quite expirienced dev. I installed it with npm problem seems the
debugging code for hotplug you uncommented with if(false) the require
statmemts within are still tried to get substituted. As this code fragment
is not within min.js patching the node_modules dir got it working. But its
more a workarround :) would be nice if you could fix this so i can easy use
it in production without creating an own release :)

Am 02.08.2017 7:17 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by dzwillia** [comment]
Can you point me to a file or show me what code is causing this?

**Comment by Gr33nbl00d** [comment]
I will have a closer look tomorrow it might have todo with your build setup
regarding webpack. In your dist folder in the unminified version i think
this code makes trouble:

if(false) {
 // When the styles change, update the <style> tags
 if(!content.locals) {
   module.hot.accept("!!../../node_modules/css-loader/index.js!../../node_modules/vue-loader/lib/style-compiler/index.js?{\"id\":\"data-v-f8f101d2\",\"scoped\":false,\"hasInlineConfig\":true}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Spinner.vue",
function() {
     var newContent =
require("!!../../node_modules/css-loader/index.js!../../node_modules/vue-loader/lib/style-compiler/index.js?{\"id\":\"data-v-f8f101d2\",\"scoped\":false,\"hasInlineConfig\":true}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Spinner.vue");
     if(typeof newContent === 'string') newContent = [[module.id,
newContent, '']];
     update(newContent);
   });
 }

Not sure why as it is more or less dead code but i guess the require
statement is tried to get substituted even if it is never used.

Florian

Am 02.08.2017 9:29 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by dzwillia** [comment]
OK. Yeah, this is definitely code that is automatically included via the webpack build process. I'll take a look at my build scripts to see what's going on.

Yeah I agree -- I'm unsure why this code would cause any problems, though, as it is inside a dead code if statement and shouldn't ever be executed.

I have a basic test file that works with both files. I'll post a link to it for you to take a look.

If you're using ES6 imports, this file is never referenced and if you're using global script tags, the minified JS file is what you'd want to use, so I might just remove this file from the repo altogether since it doesn't provide much purpose.

**Comment by Gr33nbl00d** [comment]
Im using require statement so close to es6 imports. as require is no native
javascript i guess it gets substituted even if it is not used because its
more or less done in precompile. I think you referenced this file in
package.json

"main": "dist/vue-simple-spinner.js"

Thanks for having a look :)

Am 02.08.2017 9:50 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by dzwillia** [comment]
Ah, that makes a lot of sense. I kinda jumped straight into ES6 imports from global JS includes and haven't tested it with RequireJS or the like, so I'd certainly appreciate any help you can be in ironing it out.

**Comment by dzwillia** [comment]
I just tested it with the following simple example and it works as a global include, so it's definitely something with the require() syntax that is upsetting it:

``` html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-simple-spinner - A simple, flexible spinner for Vue.js</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="A simple, flexible spinner for Vue.js">

    <meta name="twitter:title" content="dzwillia/vue-simple-spinner">
    <meta name="twitter:description" content="A simple, flexible spinner for Vue.js">

    <meta property="og:title" content="dzwillia/vue-simple-spinner">
    <meta property="og:url" content="https://github.com/dzwillia/vue-simple-spinner/">
    <meta property="og:description" content="A simple, flexible spinner for Vue.js">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tachyons/4.6.1/tachyons.min.css" integrity="sha256-eu1dpzpUytdOAUmB67Qi3mBb6HFjruP8BoAzk4lKiSc=" crossorigin="anonymous" />
    <style>
      body { padding: 40px }
    </style>
  </head>
  <body>
    <div id="app">
      <vue-simple-spinner></vue-simple-spinner>
      <vue-simple-spinner class="mt4" message="Loading..."></vue-simple-spinner>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.6/vue.js"></script>
    <script src="vue-simple-spinner.js"></script>
    <script>
      new Vue({
        el: '#app'
      });
    </script>
  </body>
</html>
```

**Comment by Gr33nbl00d** [comment]
Ok tomorrow when im at work (im from germany) so about in 10hours i will
try to put a simple node app together. Im using require directly in node js
with browseriy so not on client side. Im quite sure it has something to do
with webpack config. :)

Am 02.08.2017 9:58 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by dzwillia** [comment]
Sounds good.

One more quick question for you: was your temporary fix above to simply rename `vue-simple-spinner.min.js` to `vue-simple-spinner.js`?

**Comment by Gr33nbl00d** [comment]
Exactly this was my fix i looked up the css-loader require in the
unminified version and than found out it did not exist in the minified
version. So i simply remaned both files (exchanged them)

Am 02.08.2017 11:01 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by Gr33nbl00d** [comment]
I fixed it by adding the LoaderOptionsPluginConfig also to debug build, you
have a pull request from me :)

2017-08-02 23:18 GMT+02:00 Florian Röttges <florian.roettges@googlemail.com>
:

**Comment by dzwillia** [comment]
I've merged your pull request. I cleaned up the logic just a bit to make it more concise. I've pushed a new build (v1.2.2) which should work for you if you get the latest from NPM.

**Comment by Gr33nbl00d** [comment]
Cool :) Thank you! Unfortunatly im already at home but i will try it
tomorrow :)

Am 03.08.2017 5:17 nachm. schrieb "Dave Williams" <notifications@github.com

**Comment by Gr33nbl00d** [comment]
Just tested it today and it works :) thank you very much :)
