### ISSUE TITLE
How do you start and stop spinner?

### ISSUE THREAD

**Issue by amchconsult** [dzwillia/vue-simple-spinner#31]
Hi, 
How do you start and stop spinner?
The example button on bottom of demo don't work.
If you can give an example.
Thank you

**Comment by dzwillia** [comment]
Hi there!

Thanks for your interest in `vue-simple-spinner`.

The spinner itself isn't designed to be started or stopped. The "Pause" and "Start" buttons are there in case you like one of the random spinners that is created and you want to be able to copy the props. I probably should have been a bit more clear about this on the demo page.

I suppose if you wanted to emulate starting and stopping the spinner, you could specify an extremely long speed (100000s), which would basically make the spinner appear as though it has stopped.

Hope that helps...

Enjoy!
