### ISSUE TITLE
line-size not change

### ISSUE THREAD

**Issue by M0H3N** [dzwillia/vue-simple-spinner#6]
I want to change the line size . I added line-size="88" to spinner element but this error happens : 

```
Invalid prop: type check failed for prop "lineSize". Expected Number, got String.
```

**Comment by ReynerHL** [comment]
Try with **:line-size="88"** instead (note the **:** ). Your error seems like you have not using right the property binding. Hope this help.

**Comment by M0H3N** [comment]
@ReynerHL
I tried that bot nothing happened.

**Comment by ReynerHL** [comment]
@M0H3N can you please share more info? (some code with a fiddle or something like that would be helpful).

**Comment by dzwillia** [comment]
Hi there!

@ReynerHL is correct. If you use `:line-size="88"`, it should work. This is explained in the Vue.js docs on how to use [dynamic props](https://vuejs.org/v2/guide/components.html#Dynamic-Props). Long and short is that if you don't include the `:`, it will be interpolated as a string.

If you're still having issue, please feel free to copy/paste your code here or create a JsFiddle and I can take a look at it.

**Comment by dzwillia** [comment]
Also, if you go to the [JsFiddle](http://jsfiddle.net/dzwillia/kc5ka8zu/), I created, you should be able to mess around with some of those examples. I just tried adding `:line-size="88"` to the first spinner on that page and reloading and it worked perfectly.

**Comment by M0H3N** [comment]
this is the element code : 
```
<spinner  :line-size="88" size="massive" line-fg-color="#039be5" message="please wait..."></spinner>
```

**Comment by ReynerHL** [comment]
@M0H3N I've just put your code with some modification (only changed **spinner** by **vue-simple-spinner**) in the @dzwillia JsFiddle example and it works.

Can you please ensure that you have already loaded this VueJS package and not have any other "spinner" instead?

**Comment by dzwillia** [comment]
@M0H3N, you all squared away? Definitely doesn't appear to be an issue with the spinner, so I'm going to close this issue. Feel free to ping this thread again if you need a figuring anything else out.
