### ISSUE TITLE
Using the spinner in single file components 

### ISSUE THREAD

**Issue by DavidBarishev** [dzwillia/vue-simple-spinner#8]
Hello !
I tried using the spinner in a vue file, but your example for es6. did not work.

I did get it working, and you could include this in your readme for future use.
In .vue file : 
```html
<template>
          <vue-simple-spinner></vue-simple-spinner>
</template>

<script>
import Spinner from 'vue-simple-spinner'
export default {
  components: {
    'vue-simple-spinner': Spinner
  }
}
</script>

<style></style>
```
Note the registration of the component is with its name and not: `components: {Spinner}`, since this will cause it to make a new property with the name Spinner, and not `vue-simple-spinner`.

**Comment by dzwillia** [comment]
Hi David!

Thanks for your interest in vue-simple-spinner!

I'm not sure why the example included in my docs didn't work for you. It follows the [single file component example](https://vuejs.org/v2/guide/single-file-components.html) perfectly. In particular, when using ES6, there's no reason you shouldn't be able to use the named import on the `components` object.

In your example, you should be able to do the following:

```vue
<template>
  <spinner></spinner>
</template>

<script>
import Spinner from 'vue-simple-spinner'
export default {
  components: {
    Spinner
  }
}
</script>

<style></style>
```

Does this work for you?

Best,
Dave.

**Comment by DavidBarishev** [comment]
Yup, you are right.
I just got confused and tried to use the `vue-simple-spinner` tag instead.

**Comment by dzwillia** [comment]
No worries. Enjoy!
