### ISSUE TITLE
Not compatible with server rendering

### ISSUE THREAD

**Issue by krambuhl** [dzwillia/vue-simple-spinner#9]
The way the dist bundles are currently built, they only work when you add them directly to your html via a script tag, but not when you require from a common js driven application.  

`import SimpleSpinner from 'vue-simple-spinner'` points to the `dist/vue-simple-spinner.js` which is not useful when importing into a common js project.  This is because the dist files are webpack bundles, not the actual spinner module, and includes a bunch of data one wouldn't need if they are doing their own bundling (including some server killing references to `document`).

Currently, to use this module inside of a node project you have to reference the actual source file `import SimpleSpinner from 'vue-simple-spinner/src/components/Spinner.vue'` which is less than ideal. 

My thought is that the dist files would normally be downloaded directly, not through npm, so setting your package.json main to the source component would better capture how most folks will be using your module.   My expectations when I looked at this project was that `import SimpleSpinner from 'vue-simple-spinner'` would give the me just the vue component, nothing more.

**Comment by dzwillia** [comment]
Hi there!

Thanks for your interest in vue-simple-spinner!

I'm pretty sure the way I'm doing this is pretty standard. I use Webpack to build it using [UMD](https://github.com/umdjs/umd), so it should work for AMD, CommonJS as well as a gobal export on the `window` object.

> import SimpleSpinner from 'vue-simple-spinner' points to the dist/vue-simple-spinner.js which is not useful when importing into a common js project.

Hmm... this is actually the way almost all of the Vue.js repos I've see do it. Here are just a few examples of projects that do things this way:

* [Element](https://github.com/ElemeFE/element)
* [Vuetify](https://github.com/vuetifyjs/vuetify)
* [Vue Material](https://github.com/vuematerial/vue-material)
* [Keen UI](https://github.com/JosephusPaye/Keen-UI)
* [Quasar](https://github.com/quasarframework/quasar)

> Currently, to use this module inside of a node project you have to reference the actual source file import SimpleSpinner from 'vue-simple-spinner/src/components/Spinner.vue' which is less than ideal.

I've used it in a CommonJS environment and it works great. If you take a look at the main include [src/index.js](https://github.com/dzwillia/vue-simple-spinner/blob/master/src/index.js), you'll see that all that is being exported to the JS file is the `Spinner.vue` file -- there's no extra "cruft" included; only the Vue component is exported.

Happy to help if you're still having issues getting it working. Just let me know! :-)

**Comment by dzwillia** [comment]
Ah, gotcha. This is very helpful to know. I'll be honest, I've read a little bit here and there about SSR, but I have yet to actually delve into into it in a project. Do you happen to know of any resources that might help me create a quick testbed for fixing this issue with SSR?

**Comment by krambuhl** [comment]
Using `style-loader` has the benefit of not requiring any additional css files in the dist, but will cause problems in a node environment.  If you were to use a tool like `extract-text-webpack-plugin` you could bundle `vue-simple-spinner.js` and `vue-simple-spinner.css` separately.  There would be the surface downside that css isn't included by default, but it would dramatically reduce your bundle size.  This would also allow the consumer of your module decide how they want into include that css, instead of it being dictated by the module. 

Take a look at the dist and webpack config of Keen UI, that's what I would expect. https://github.com/JosephusPaye/Keen-UI/tree/next/dist

**Comment by krambuhl** [comment]
That change would also require an update to the README to explain that including CSS is up to the consumer of this module. (ala. https://github.com/JosephusPaye/Keen-UI#es6)

Also, I don't want to ask for anything I wouldn't do myself. If the solution in the keen-ui setup would be acceptable by you, I'd be happy to make the PR!

**Comment by dzwillia** [comment]
This is very helpful feedback. This is the only CSS code in the component file:

```css
<style>
  .vue-simple-spinner {
    transition: all 0.3s linear;
  }

  @keyframes vue-simple-spinner-spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
</style>
```

I'd be loathe to include a separate CSS file for such a little amount of CSS, however, I'm not sure if there's anyway to inline a CSS transition... :-/

Let me think about this and see what I can do...

Thanks again for the feedback.

**Comment by dzwillia** [comment]
Well... that didn't take long. Just ran into this issue myself using Nuxt.js for a templates area on our new website. :-)

@krambuhl, do you or anyone you know how any ideas for a clever solution to be able to include this by default for those running in the browser while not causing SSR apps to fail?

**Comment by krambuhl** [comment]
I would suggest bitting the bullet and making a breaking change. The benefit of a much smaller bundle and more flexible integration strategy seems to outweigh the downsides of asking people to upgrade.

You could inject your custom css into the page with template strings and hand-rolled code to inject the `<style>` tag only in the browser, but the consumer of the library would not have any power to cache that css without caching your whole js file.  I would not recommend this route, but it would give you a more server compatible codebase and would not change how someone integrates your component.

**Comment by kernelcoredump** [comment]
The current dist js files also performs inline addition of styles, which gives an error when there's a restrictive CSP (disallowed 'unsafe-inline').

So in our setup, we also reference the source, and let vue-loader extract the CSS from the single file component for production builds.

**Comment by daniplaninc** [comment]
Anyone using this with nuxt currently?

**Comment by weotch** [comment]
> Anyone using this with nuxt currently?

It's working with me when imported into another component like this:

```js
import spinner from 'vue-simple-spinner/src/components/Spinner.vue'
```

**Comment by daniplaninc** [comment]
Ok thanks, that works for me too. I was just wondering if there was another way to do it
